class Concerns::Css
  PROPERTIES = ["backgroundAttachment", "backgroundClip", "backgroundColor", "backgroundImage",
    "backgroundOrigin", "backgroundPosition", "backgroundRepeat", "backgroundSize",
    "borderBottomColor", "borderBottomLeftRadius", "borderBottomRightRadius", "borderBottomStyle",
    "borderBottomWidth", "borderCollapse", "borderImageOutset", "borderImageRepeat",
    "borderImageSlice", "borderImageSource", "borderImageWidth", "borderLeftColor",
    "borderLeftStyle", "borderLeftWidth", "borderRightColor", "borderRightStyle",
    "borderRightWidth", "borderTopColor", "borderTopLeftRadius", "borderTopRightRadius",
    "borderTopStyle", "borderTopWidth", "bottom", "boxShadow", "boxSizing", "captionSide",
    "clear", "clip", "color", "cursor", "direction", "display", "emptyCells", "float",
    "fontFamily", "fontKerning", "fontSize", "fontStyle", "fontVariant", "fontVariantLigatures",
    "fontWeight", "height", "imageRendering", "left", "letterSpacing", "lineHeight", "listStyleImage",
    "listStylePosition", "listStyleType", "marginBottom", "marginLeft", "marginRight", "marginTop",
    "maxHeight", "maxWidth", "minHeight", "minWidth", "objectFit", "objectPosition", "opacity",
    "orphans", "outlineColor", "outlineOffset", "outlineStyle", "outlineWidth", "overflowWrap",
    "overflowX", "overflowY", "paddingBottom", "paddingLeft", "paddingRight", "paddingTop",
    "pageBreakAfter", "pageBreakBefore", "pageBreakInside", "pointerEvents", "position",
    "resize", "right", "speak", "tableLayout", "tabSize", "textAlign", "textDecoration",
    "textIndent", "textRendering", "textShadow", "textOverflow", "textTransform", "top",
    "transitionDelay", "transitionDuration", "transitionProperty", "transitionTimingFunction",
    "unicodeBidi", "verticalAlign", "visibility", "whiteSpace", "widows", "width", "wordBreak",
    "wordSpacing", "wordWrap", "zIndex", "zoom", "WebkitAnimationDelay", "WebkitAnimationDirection",
    "WebkitAnimationDuration", "WebkitAnimationFillMode", "WebkitAnimationIterationCount",
    "WebkitAnimationName", "WebkitAnimationPlayState", "WebkitAnimationTimingFunction",
    "WebkitAppearance", "WebkitBackfaceVisibility", "WebkitBackgroundClip", "WebkitBackgroundComposite",
    "WebkitBackgroundOrigin", "WebkitBackgroundSize", "WebkitBorderFit", "WebkitBorderHorizontalSpacing",
    "WebkitBorderImage", "WebkitBorderVerticalSpacing", "WebkitBoxAlign", "WebkitBoxDecorationBreak",
    "WebkitBoxDirection", "WebkitBoxFlex", "WebkitBoxFlexGroup", "WebkitBoxLines", "WebkitBoxOrdinalGroup",
    "WebkitBoxOrient", "WebkitBoxPack", "WebkitBoxReflect", "WebkitBoxShadow", "WebkitClipPath",
    "WebkitColumnBreakAfter", "WebkitColumnBreakBefore", "WebkitColumnBreakInside", "WebkitColumnAxis",
    "WebkitColumnCount", "WebkitColumnGap", "WebkitColumnProgression", "WebkitColumnRuleColor",
    "WebkitColumnRuleStyle", "WebkitColumnRuleWidth", "WebkitColumnSpan", "WebkitColumnWidth",
    "WebkitFilter", "alignContent", "alignItems", "alignSelf", "flexBasis", "flexGrow",
    "flexShrink", "flexDirection", "flexWrap", "justifyContent", "WebkitFontSmoothing",
    "WebkitHighlight", "WebkitHyphenateCharacter", "WebkitLineBoxContain", "WebkitLineBreak",
    "WebkitLineClamp", "WebkitLocale", "WebkitMarginBeforeCollapse", "WebkitMarginAfterCollapse",
    "WebkitMaskBoxImage", "WebkitMaskBoxImageOutset", "WebkitMaskBoxImageRepeat",
    "WebkitMaskBoxImageSlice", "WebkitMaskBoxImageSource", "WebkitMaskBoxImageWidth",
    "WebkitMaskClip", "WebkitMaskComposite", "WebkitMaskImage", "WebkitMaskOrigin",
    "WebkitMaskPosition", "WebkitMaskRepeat", "WebkitMaskSize", "order", "WebkitPerspective",
    "WebkitPerspectiveOrigin", "WebkitPrintColorAdjust", "WebkitRtlOrdering", "WebkitTapHighlightColor",
    "WebkitTextCombine", "WebkitTextDecorationsInEffect", "WebkitTextEmphasisColor", "WebkitTextEmphasisPosition",
    "WebkitTextEmphasisStyle", "WebkitTextFillColor", "WebkitTextOrientation", "WebkitTextSecurity",
    "WebkitTextStrokeColor", "WebkitTextStrokeWidth", "WebkitTransform", "WebkitTransformOrigin",
    "WebkitTransformStyle", "WebkitTransitionDelay", "WebkitTransitionDuration", "WebkitTransitionProperty",
    "WebkitTransitionTimingFunction", "WebkitUserDrag", "WebkitUserModify", "WebkitUserSelect",
    "WebkitWritingMode", "WebkitAppRegion", "bufferedRendering", "clipPath", "clipRule",
    "mask", "filter", "floodColor", "floodOpacity", "lightingColor", "stopColor",
    "stopOpacity", "colorInterpolation", "colorInterpolationFilters", "colorRendering",
    "fill", "fillOpacity", "fillRule", "markerEnd", "markerMid", "markerStart", "maskType",
    "shapeRendering", "stroke", "strokeDasharray", "strokeDashoffset", "strokeLinecap",
    "strokeLinejoin", "strokeMiterlimit", "strokeOpacity", "strokeWidth", "alignmentBaseline",
    "baselineShift", "dominantBaseline", "kerning", "textAnchor", "writingMode",
    "glyphOrientationHorizontal", "glyphOrientationVertical", "vectorEffect"]
end